export const PREPARE_FORM_STEPS = [
  "Datos generales",
  "Documentos",
  "Motor",
  "Correas",
  "Tapas",
  "Transmisión de potencia",
  "Batería",
  "Direccionales",
  "Luces",
  "Suspensión y dirección",
  "Limpiaparabrisas",
  "Frenos",
  "Llantas",
  "Espejos",
  "Salidas de emergencia, puertas",
  "Pito",
  "Niveles de fluido",
  "Filtros húmedos y secos",
  "Seguridad pasiva",
  "Última fecha de mantenimiento",
  "Extintor",
  "Herramientas",
  "Señales",
  "Chaleco",
  "Botiquín",
  "Residuos",
];
