import {
  CompanyData,
  PrepareFormRequest,
  UserData,
} from "@ncl/app/shared/models";

export const prepareFormInitialValues = (
  user: UserData | null,
  company?: CompanyData | null,
): PrepareFormRequest => ({
  licensePlate: "",
  internalNumber: "",
  companyId: user?.companyId || "",
  companyName: company?.name || "",
  companyCity: company?.city || "",
  preparerName: user ? `${user?.name} ${user?.lastName}` : "",
  preparerID: user?.id || "",
  driverName: "",
  isLicenseTransitValid: "",
  licenseTransitObs: "",
  licenseTransitFile: null,
  isSOATValid: "",
  SOATObs: "",
  SOATFile: null,
  isPrevRevisionValid: "",
  prevRevisionObs: "",
  prevRevisionFile: null,
  isRTMAndECValid: "",
  RTMAndECObs: "",
  RTMAndECFile: null,
  isPolicyRCEAndRCCValid: "",
  policyRCEAndRCCObs: "",
  policyRCEAndRCCFile: null,
  isOperationCardValid: "",
  operationCardObs: "",
  operationCardFile: null,
  isDriverLicenseValid: "",
  driverLicenseObs: "",
  driverLicenseFile: null,
  isEngineLeaksValid: "",
  engineLeaksObs: "",
  engineLeaksFile: null,
  isBeltTensionValid: "",
  beltTensionObs: "",
  beltTensionFile: null,
  isFuelCapsValid: "",
  fuelCapsObs: "",
  fuelCapsFile: null,
  isTransmissionStatusValid: "",
  transmissionStatusObs: "",
  transmissionStatusFile: null,
  isBatteryStatusValid: "",
  batteryStatusObs: "",
  batteryStatusFile: null,
  isFrontTurnSignalsValid: "",
  frontTurnSignalsObs: "",
  frontTurnSignalsFile: null,
  isRearTurnSignalsValid: "",
  rearTurnSignalsObs: "",
  rearTurnSignalsFile: null,
  isHighLightsValid: "",
  highLightsObs: "",
  highLightsFile: null,
  isLowLightsValid: "",
  lowLightsObs: "",
  lowLightsFile: null,
  isStopsValid: "",
  stopsObs: "",
  stopsFile: null,
  isReverseLightValid: "",
  reverseLightObs: "",
  reverseLightFile: null,
  isParkingLightsValid: "",
  parkingLightsObs: "",
  parkingLightsFile: null,
  isDashboardLightsValid: "",
  dashboardLightsObs: "",
  dashboardLightsFile: null,
  isSuspensionStatusValid: "",
  suspensionStatusObs: "",
  suspensionStatusFile: null,
  isWiperStatusValid: "",
  wiperStatusObs: "",
  wiperStatusFile: null,
  isMainBrakesStatusValid: "",
  mainBrakesStatusObs: "",
  mainBrakesStatusFile: null,
  isEmergencyBrakesStatusValid: "",
  emergencyBrakesStatusObs: "",
  emergencyBrakesStatusFile: null,
  isFrontTyresStatusValid: "",
  frontTyresStatusObs: "",
  frontTyresStatusFile: null,
  isRearTyresStatusValid: "",
  rearTyresStatusObs: "",
  rearTyresStatusFile: null,
  isSpareTyreStatusValid: "",
  spareTyreStatusObs: "",
  spareTyreStatusFile: null,
  isSideMirrorsStatusValid: "",
  sideMirrorsStatusObs: "",
  sideMirrorsStatusFile: null,
  isRearviewStatusValid: "",
  rearviewStatusObs: "",
  rearviewStatusFile: null,
});
