export interface PrepareFormRequest {
  licensePlate: string;
  internalNumber: string;
  companyId: string;
  companyName: string;
  companyCity: string;
  preparerName: string;
  preparerID: string;
  driverName: string;
  isLicenseTransitValid: string;
  licenseTransitObs?: string;
  licenseTransitFile?: File | null;
  isSOATValid: string;
  SOATObs?: string;
  SOATFile?: File | null;
  isPrevRevisionValid: string;
  prevRevisionObs?: string;
  prevRevisionFile?: File | null;
  isRTMAndECValid: string;
  RTMAndECObs?: string;
  RTMAndECFile?: File | null;
  isPolicyRCEAndRCCValid: string;
  policyRCEAndRCCObs?: string;
  policyRCEAndRCCFile?: File | null;
  isOperationCardValid: string;
  operationCardObs?: string;
  operationCardFile?: File | null;
  isDriverLicenseValid: string;
  driverLicenseObs?: string;
  driverLicenseFile?: File | null;
  isEngineLeaksValid: string;
  engineLeaksObs?: string;
  engineLeaksFile?: File | null;
  isBeltTensionValid: string;
  beltTensionObs?: string;
  beltTensionFile?: File | null;
  isFuelCapsValid: string;
  fuelCapsObs?: string;
  fuelCapsFile?: File | null;
  isTransmissionStatusValid: string;
  transmissionStatusObs?: string;
  transmissionStatusFile?: File | null;
  isBatteryStatusValid: string;
  batteryStatusObs?: string;
  batteryStatusFile?: File | null;
  isFrontTurnSignalsValid: string;
  frontTurnSignalsObs?: string;
  frontTurnSignalsFile?: File | null;
  isRearTurnSignalsValid: string;
  rearTurnSignalsObs?: string;
  rearTurnSignalsFile?: File | null;
  isHighLightsValid: string;
  highLightsObs?: string;
  highLightsFile?: File | null;
  isLowLightsValid: string;
  lowLightsObs?: string;
  lowLightsFile?: File | null;
  isStopsValid: string;
  stopsObs?: string;
  stopsFile?: File | null;
  isReverseLightValid: string;
  reverseLightObs?: string;
  reverseLightFile?: File | null;
  isParkingLightsValid: string;
  parkingLightsObs?: string;
  parkingLightsFile?: File | null;
  isDashboardLightsValid: string;
  dashboardLightsObs?: string;
  dashboardLightsFile?: File | null;
  isSuspensionStatusValid: string;
  suspensionStatusObs?: string;
  suspensionStatusFile?: File | null;
  isPowerSteeringStatusValid: string;
  powerSteeringStatusObs?: string;
  powerSteeringStatusFile?: File | null;
  isWiperStatusValid: string;
  wiperStatusObs?: string;
  wiperStatusFile?: File | null;
  isMainBrakesStatusValid: string;
  mainBrakesStatusObs?: string;
  mainBrakesStatusFile?: File | null;
  isEmergencyBrakesStatusValid: string;
  emergencyBrakesStatusObs?: string;
  emergencyBrakesStatusFile?: File | null;
  isFrontTyresStatusValid: string;
  frontTyresStatusObs?: string;
  frontTyresStatusFile?: File | null;
  isRearTyresStatusValid: string;
  rearTyresStatusObs?: string;
  rearTyresStatusFile?: File | null;
  isSpareTyreStatusValid: string;
  spareTyreStatusObs?: string;
  spareTyreStatusFile?: File | null;
  isSideMirrorsStatusValid: string;
  sideMirrorsStatusObs?: string;
  sideMirrorsStatusFile?: File | null;
  isRearviewStatusValid: string;
  rearviewStatusObs?: string;
  rearviewStatusFile?: File | null;
  isEmergencyExitValid: string;
  emergencyExitObs?: string;
  emergencyExitFile?: File | null;
  isHornValid: string;
  hornObs?: string;
  hornFile?: File | null;
  isFluidLevelBrakesValid: string;
  fluidLevelBrakesObs?: string;
  fluidLevelBrakesFile?: File | null;
  isFluidLevelOilValid: string;
  fluidLevelOilObs?: string;
  fluidLevelOilFile?: File | null;
  isFluidLevelRefrigerantValid: string;
  fluidLevelRefrigerantObs?: string;
  fluidLevelRefrigerantFile?: File | null;
  isDryAndWetFiltersValid: string;
  dryAndWetFiltersObs?: string;
  dryAndWetFiltersFile?: File | null;
  isPassiveSafetyValid: string;
  passiveSafetyObs?: string;
  passiveSafetyFile?: File | null;
  // Última fecha de mantenimiento
  lastOilChangeDate: string;
  isLastOilChangeValid: string;
  lastOilChangeObs?: string;
  lastOilChangeFile?: File | null;
  lastCleanDate: string;
  isLastCleanValid: string;
  lastCleanObs?: string;
  lastCleanFile?: File | null;
  lastAlignmentBalanceDate: string;
  isLastAlignmentBalanceValid: string;
  lastAlignmentBalanceObs?: string;
  lastAlignmentBalanceFile?: File | null;
  lastSyncDate: string;
  isLastSyncValid: string;
  lastSyncObs?: string;
  lastSyncFile?: File | null;
  lastTyreChangesDate: string;
  isLastTyreChangesValid: string;
  lastTyreChangesObs?: string;
  lastTyreChangesFile?: File | null;
  // Extintor
  isExtinguisherValid: string;
  extinguisherObs?: string;
  extinguisherFile?: File | null;
  isExtinguisherSizeValid: string;
  extinguisherSizeObs?: string;
  extinguisherSizeFile?: File | null;
  // Herramientas
  isPliersValid: string;
  pliersObs?: string;
  pliersFile?: File | null;
  isScrewdriversValid: string;
  screwdriversObs?: string;
  screwdriversFile?: File | null;
  isWrenchValid: string;
  wrenchObs?: string;
  wrenchFile?: File | null;
  isCrossPieceValid: string;
  crossPieceObs?: string;
  crossPieceFile?: File | null;
  isJackValid: string;
  jackObs?: string;
  jackFile?: File | null;
  isTyreShockValid: string;
  tyreShockObs?: string;
  tyreShockFile?: File | null;
  // Señales
  isWarningSignsValid: string;
  warningSignsObs?: string;
  warningSignsFile?: File | null;
  // Chaleco
  isSafetyVestsValid: string;
  safetyVestsObs?: string;
  safetyVestsFile?: File | null;
  // Botiquín
  isFirstAidKitValid: string;
  firstAidKitObs?: string;
  firstAidKitFile?: File | null;
  // Residuos
  isWasteValid: string;
  wasteObs?: string;
  wasteFile?: File | null;
}
